version: '2.2'

services:
  redis:
    image: redis
    ports:
      - 6379:6379

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686
      - 14268:14268
      - 14250:14250
      - 9411:9411
      - 4317:4317
      - 4318:4318

    environment:
      - COLLECTOR_OTLP_ENABLED=true
