---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: go-sample-app
  name: go-sample-app
spec:
  ports:
  - port: 9090
    protocol: TCP
    targetPort: 9090
  selector:
    app: go-sample-app
  type: NodePort
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: go-sample-app
  name: go-sample-app
  # namespace: instana-agent
spec:
  replicas: 3
  selector:
    matchLabels:
      app: go-sample-app
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-sample-app
    spec:
      containers:
      - image: go-sample-app:1.0.3
        name: go-sample-app
        resources: {}
status: {}
